name: CI

# Inspiration:
# https://github.com/alexdiliberto/ember-transformicons/blob/master/.github/workflows/ci.yml
on:
  pull_request:
  push:
    # filtering branches here prevents duplicate builds from pull_request and push
    branches:
      - master

env:
  CI: true

jobs:
  lint:
    if: "! contains(toJSON(github.event.commitns.*.message), '[skip ci]')"
    name: Lint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1 # for shallow
    - uses: volta-cli/action@v1
    - name: Install
      run: yarn install
    - name: ESLint
      run: yarn lint:js
    # - name: Templates
    #   run: yarn lint:hbs
    - name: Types
      run: yarn tsc --noEmit
    - uses: wagoid/commitlint-github-action@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GH_PAT }}


  publish:
    name: Release
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    needs: [lint]

    steps:
    - uses: actions/checkout@v1 # for shallow
    - uses: volta-cli/action@v1
    - run: yarn install
    - name: Release
      env:
        GITHUB_TOKEN: ${{ secrets.GH_PAT }}
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      run: yarn semantic-release
